# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
 
# Site settings
title: Beck Programming Blog
email: matheus.alencabeck@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Did you find any error or misconception? Help me to correct it! 😊 This is an open-source project, you can edit the text in the .md files directly from GitHub and open a pull-request. This is a simple way to contribute with the software community! 
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://matheus-beck.github.io/" # the base hostname & protocol for your site
linkedin_username: matheus-beck
github_username: matheus-beck

plugins:
  - jemoji

# Build settings
markdown: kramdown
