# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Beck Programming Blog
email: matheus.alencabeck@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm a computer engineering student at Federal University of Bahia who loves software development. 
  This blog has the purpose of helping me track my programming learning journey and to improve my learning process by forcing me to teach someone else what I've been learning. 
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://matheus-beck.github.io/" # the base hostname & protocol for your site
linkedin_username: matheus-beck
github_username:  matheus-beck

plugins:
  - jemoji

# Build settings
markdown: kramdown
